---

networks:
  private-network:
    driver: bridge
    name: private-network

services:
  # Jenkins container
  jenkins:
    build: .
    image: myjenkins-blueocean:v1
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    container_name: jenkins-blueocean
    restart: on-failure
    networks:
      - private-network
    volumes:
      - ./jenkins-volumes/jenkins-data:/var/jenkins_home
      - ./jenkins-volumes/jenkins-docker-certs:/certs/client:ro

  # Docker jenkins agent container
  jenkins-docker-agent:
    image: alpine/socat
    container_name: jenkins-docker-agent
    restart: always
    networks:
      - private-network
    ports:
      - "127.0.0.1:2376:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"

  # Prometheus container
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-volumes/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: on-failure
    container_name: prometheus
    networks:
      - private-network

  # Grafana container
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-volumes/grafana-data:/var/lib/grafana
      - ./grafana-volumes/grafana-provisioning:/etc/grafana/provisioning
    restart: on-failure
    container_name: grafana
    networks:
      - private-network