---

networks:
  private-network:
    driver: bridge
    name: private-network

services:
  jenkins:
    build: .
    image: myjenkins-blueocean:v1
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    container_name: jenkins-blueocean
    restart: on-failure
    networks:
      - private-network
    volumes:
      - ./jenkins-volumes/jenkins-data:/var/jenkins_home
      - ./jenkins-volumes/jenkins-docker-certs:/certs/client:ro

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-volumes/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: on-failure
    container_name: prometheus
    networks:
      - private-network